# Generated by Django 4.0.1 on 2022-01-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=64)),
                ('formForText', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('important', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('promocode', models.CharField(max_length=64)),
                ('creationTime', models.DateTimeField()),
                ('expirationTime', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.city')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resources')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('mainText', models.TextField()),
                ('creationTime', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.city')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resources')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MissingPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('clothes', models.TextField()),
                ('specCharacteristics', models.TextField()),
                ('characteristics', models.TextField()),
                ('lastLocation', models.CharField(max_length=150)),
                ('dateOfBirth', models.DateField()),
                ('sex', models.CharField(max_length=12)),
                ('telephone', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=12)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.city')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resources')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.city')),
            ],
        ),
    ]
