# Generated by Django 3.2.9 on 2021-12-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('promocode', models.CharField(max_length=64)),
                ('creationTime', models.DateTimeField()),
                ('expirationTime', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.city')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resources')),
            ],
        ),
    ]
