# Generated by Django 4.0.1 on 2022-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_user_login_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=64),
        ),
    ]
