# Generated by Django 3.2.9 on 2021-12-11 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_tag_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MissingPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('clothes', models.TextField()),
                ('specCharacteristics', models.TextField()),
                ('characteristics', models.TextField()),
                ('lastLocation', models.CharField(max_length=150)),
                ('dateOfBirth', models.DateField()),
                ('sex', models.CharField(max_length=12)),
                ('telephone', models.CharField(max_length=12)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.city')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.resources')),
            ],
        ),
    ]
