# Generated by Django 3.2.9 on 2021-12-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='creationTime',
            field=models.DateField(),
        ),
    ]
