# Generated by Django 3.2.9 on 2021-12-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_newsarticles_creationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='creationTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='expirationTime',
            field=models.DateField(),
        ),
    ]
