# Generated by Django 3.2.9 on 2021-12-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_missingpeople_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpeople',
            name='status',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
